 services:

      # Oracle service (label used to access the service container)
      oracle:

        # Docker Hub image
        image: gvenzl/oracle-xe:18.4.0-slim

        # Provide passwords and other environment variables to container
        environment:
          ORACLE_PASSWORD: oracle
          ORACLE_CHARACTERSET: AL32UTF8
          # ALTER SESSION SET "ORACLE_SCRIPT"=true

        # Forward Oracle port
        ports: 
          - 1521:1521

# After your service is created, you can connect to it via the following properties:

#     Hostname:
#         oracle (from within another container)
#         localhost or 127.0.0.1 (from the host directly)
#     Port: 1521
#     Service name: XEPDB1
#     Database App User: my_user
#     Database App Password: oracle

# https://hub.docker.com/r/gvenzl/oracle-xe